create table tb_dealerships (id_dealership int8 generated by default as identity, name varchar(255), id_federative_unit int8, primary key (id_dealership));
create table tb_federative_units (id_federative_unit int8 generated by default as identity, name varchar(255), prefix varchar(255), primary key (id_federative_unit));
alter table if exists tb_dealerships add constraint FK10x6pkdy4e5yhc6cdihi6umtg foreign key (id_federative_unit) references tb_federative_units;
